name: biomarker

channels:
  - conda-forge
  - defaults
  - anaconda
  - bioconda
  - r

dependencies:
  - conda-forge::awscli=1.25.60
  - conda-forge::boto3=1.24.59
  - conda-forge::fsspec=2022.11.0
  - conda-forge::nb_conda_kernels=2.3.1
  - conda-forge::notebook=6.4.12
  - conda-forge::matplotlib=3.6.1
  - conda-forge::scikit-learn=1.1.2
  - conda-forge::scipy=1.9.1
  - conda-forge::s3fs=2022.11.0
  - conda-forge::numpy=1.23.3
  - conda-forge::pandas=1.5.0
  - conda-forge::pandoc=2.17.1.1
  - conda-forge::rpy2=3.5.1
  - conda-forge::r-base=4.1.2
  - conda-forge::r-here 1.0.1
  - conda-forge::r-irkernel=1.3
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-svglite=2.1.0
  - conda-forge::r-tidyverse=1.3.1
